/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CentralRouteImport } from './routes/central'
import { Route as ConcursoRouteImport } from './routes/concurso'
import { Route as ConcursosRouteImport } from './routes/concursos'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DisponibilidadeRouteImport } from './routes/disponibilidade'
import { Route as EncontrarRouteImport } from './routes/encontrar'
import { Route as EnviarEditalRouteImport } from './routes/enviar-edital'
import { Route as EstudarRouteImport } from './routes/estudar'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as PlanoCompletoRouteImport } from './routes/plano-completo'
import { Route as QuestaoQuestaoIdRouteImport } from './routes/questao.$questaoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcursoRoute = ConcursoRouteImport.update({
  id: '/concurso',
  path: '/concurso',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcursosRoute = ConcursosRouteImport.update({
  id: '/concursos',
  path: '/concursos',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DisponibilidadeRoute = DisponibilidadeRouteImport.update({
  id: '/disponibilidade',
  path: '/disponibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const EncontrarRoute = EncontrarRouteImport.update({
  id: '/encontrar',
  path: '/encontrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarEditalRoute = EnviarEditalRouteImport.update({
  id: '/enviar-edital',
  path: '/enviar-edital',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudarRoute = EstudarRouteImport.update({
  id: '/estudar',
  path: '/estudar',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoCompletoRoute = PlanoCompletoRouteImport.update({
  id: '/plano-completo',
  path: '/plano-completo',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestaoQuestaoIdRoute = QuestaoQuestaoIdRouteImport.update({
  id: '/questao/$questaoId',
  path: '/questao/$questaoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/central': typeof CentralRoute
  '/concurso': typeof ConcursoRoute
  '/concursos': typeof ConcursosRoute
  '/cronograma': typeof CronogramaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/disponibilidade': typeof DisponibilidadeRoute
  '/encontrar': typeof EncontrarRoute
  '/enviar-edital': typeof EnviarEditalRoute
  '/estudar': typeof EstudarRoute
  '/painel': typeof PainelRoute
  '/plano': typeof PlanoRoute
  '/plano-completo': typeof PlanoCompletoRoute
  '/questao/$questaoId': typeof QuestaoQuestaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/central': typeof CentralRoute
  '/concurso': typeof ConcursoRoute
  '/concursos': typeof ConcursosRoute
  '/cronograma': typeof CronogramaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/disponibilidade': typeof DisponibilidadeRoute
  '/encontrar': typeof EncontrarRoute
  '/enviar-edital': typeof EnviarEditalRoute
  '/estudar': typeof EstudarRoute
  '/painel': typeof PainelRoute
  '/plano': typeof PlanoRoute
  '/plano-completo': typeof PlanoCompletoRoute
  '/questao/$questaoId': typeof QuestaoQuestaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/central': typeof CentralRoute
  '/concurso': typeof ConcursoRoute
  '/concursos': typeof ConcursosRoute
  '/cronograma': typeof CronogramaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/disponibilidade': typeof DisponibilidadeRoute
  '/encontrar': typeof EncontrarRoute
  '/enviar-edital': typeof EnviarEditalRoute
  '/estudar': typeof EstudarRoute
  '/painel': typeof PainelRoute
  '/plano': typeof PlanoRoute
  '/plano-completo': typeof PlanoCompletoRoute
  '/questao/$questaoId': typeof QuestaoQuestaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/central'
    | '/concurso'
    | '/concursos'
    | '/cronograma'
    | '/diagnostico'
    | '/disponibilidade'
    | '/encontrar'
    | '/enviar-edital'
    | '/estudar'
    | '/painel'
    | '/plano'
    | '/plano-completo'
    | '/questao/$questaoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/central'
    | '/concurso'
    | '/concursos'
    | '/cronograma'
    | '/diagnostico'
    | '/disponibilidade'
    | '/encontrar'
    | '/enviar-edital'
    | '/estudar'
    | '/painel'
    | '/plano'
    | '/plano-completo'
    | '/questao/$questaoId'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/central'
    | '/concurso'
    | '/concursos'
    | '/cronograma'
    | '/diagnostico'
    | '/disponibilidade'
    | '/encontrar'
    | '/enviar-edital'
    | '/estudar'
    | '/painel'
    | '/plano'
    | '/plano-completo'
    | '/questao/$questaoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CentralRoute: typeof CentralRoute
  ConcursoRoute: typeof ConcursoRoute
  ConcursosRoute: typeof ConcursosRoute
  CronogramaRoute: typeof CronogramaRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  DisponibilidadeRoute: typeof DisponibilidadeRoute
  EncontrarRoute: typeof EncontrarRoute
  EnviarEditalRoute: typeof EnviarEditalRoute
  EstudarRoute: typeof EstudarRoute
  PainelRoute: typeof PainelRoute
  PlanoRoute: typeof PlanoRoute
  PlanoCompletoRoute: typeof PlanoCompletoRoute
  QuestaoQuestaoIdRoute: typeof QuestaoQuestaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurso': {
      id: '/concurso'
      path: '/concurso'
      fullPath: '/concurso'
      preLoaderRoute: typeof ConcursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concursos': {
      id: '/concursos'
      path: '/concursos'
      fullPath: '/concursos'
      preLoaderRoute: typeof ConcursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disponibilidade': {
      id: '/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/disponibilidade'
      preLoaderRoute: typeof DisponibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encontrar': {
      id: '/encontrar'
      path: '/encontrar'
      fullPath: '/encontrar'
      preLoaderRoute: typeof EncontrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar-edital': {
      id: '/enviar-edital'
      path: '/enviar-edital'
      fullPath: '/enviar-edital'
      preLoaderRoute: typeof EnviarEditalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudar': {
      id: '/estudar'
      path: '/estudar'
      fullPath: '/estudar'
      preLoaderRoute: typeof EstudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-completo': {
      id: '/plano-completo'
      path: '/plano-completo'
      fullPath: '/plano-completo'
      preLoaderRoute: typeof PlanoCompletoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questao/$questaoId': {
      id: '/questao/$questaoId'
      path: '/questao/$questaoId'
      fullPath: '/questao/$questaoId'
      preLoaderRoute: typeof QuestaoQuestaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  CentralRoute: CentralRoute,
  ConcursoRoute: ConcursoRoute,
  ConcursosRoute: ConcursosRoute,
  CronogramaRoute: CronogramaRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  DisponibilidadeRoute: DisponibilidadeRoute,
  EncontrarRoute: EncontrarRoute,
  EnviarEditalRoute: EnviarEditalRoute,
  EstudarRoute: EstudarRoute,
  PainelRoute: PainelRoute,
  PlanoRoute: PlanoRoute,
  PlanoCompletoRoute: PlanoCompletoRoute,
  QuestaoQuestaoIdRoute: QuestaoQuestaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
